name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Downlaod Repo
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .
      - name: my-step
        run: chmod +x ci/build-app.sh && ci/build-app.sh  
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Downlaod Repo
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact
      - name: Download
        run: chmod +x ci/build-app.sh && ci/build-app.sh